version: '3'

services:
  nginx:
    image: nginx:1.20
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - dblog_static_volume:/dblog/static
      - dblog_files_volume:/dblog/files
    networks:
      - nginx_network

volumes:
  dblog_static_volume:
    external: true
  dblog_files_volume:
    external: true
networks:
  nginx_network:
    external: true
