version: '3'

services:
  dblog_nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dblog_nginx
    volumes:
      - dblog_static_volume:/dblog/static
      - dblog_files_volume:/dblog/files
    ports:
      - "80:80"
    networks:
      - nginx_network

volumes:
  dblog_static_volume:
    external: true
  dblog_files_volume:
    external: true

networks:
  nginx_network:
    external: true
